### ISSUE TITLE
Fehler wenn News/Kalender deaktiviert ist

### ISSUE THREAD

**Issue by k-webdesign** [christianbarkowsky/rel-canonical#11]
Hi Christian,

wenn man FAQ, Kalender und News deaktiviert hat, läuft man beim Updaten in einen Fehler:
![screenshot 2016-11-22 15 20 35](https://cloud.githubusercontent.com/assets/4130440/20531103/fb78a1a8-b0d5-11e6-83a0-b2cea0c534ec.png)

VG Kim

**Comment by christianbarkowsky** [comment]
b22190c9d7b8d003477d78974f45475e5cf0bce2

**Comment by k-webdesign** [comment]
Das Update funktioniert tadellos, danke :)
