### ISSUE TITLE
News Canonical funktioniert nicht  - Contao 4.6 - Warning: Cannot declare class ModuleNewsReader, because the name is already in use

### ISSUE THREAD

**Issue by tarun-uwe** [christianbarkowsky/rel-canonical#14]
Hi Christian, 

die Erweiterung funktioniert in Contao 4.6 super auf Seitenebene, aber nicht (mehr) auf News Ebene. 

Im "normalen" Modus wird der *tag* nicht eingebunden. In der App Dev wird folgende Warnung ausgegeben.
`Warning: Cannot declare class ModuleNewsReader, because the name is already in use` 
Bei der Recherche habe ich deinen Issue #13 gefunden und dachte, dass die Erweiterung auch mit 4.6 funktioniert.

Im Forum habe ich [folgendes](https://community.contao.org/de/showthread.php?72699-Core-Klasse-ContentElement-%C3%BCberschreiben-geht-nicht-mehr) gefunden, bin mir aber nicht sicher, ob das daher kommt, dass es anscheinend eine Änderung von C 4.5 auf C4.6 gab.
([ClassLoader](https://github.com/contao/contao/blob/master/DEPRECATED.md#contao-class-loader))

Ist dir ersichtlich, wieso es nicht mehr geht und kann man dir beim Fix helfen?

**Comment by christianbarkowsky** [comment]
Hallo @tarun-uwe,

der Fehler ist jetzt behoben.

**Comment by tarun-uwe** [comment]
Hi @christianbarkowsky - funktioniert super. Danke dir.
