### ISSUE TITLE
Canonical TAG an andere Stelle ausgeben

### ISSUE THREAD

**Issue by codesache** [christianbarkowsky/rel-canonical#15]
Hallo Christian,
ich würde gerne das Canonical TAG nicht im $GLOBALS['TL_HEAD'] ausgeben,
sondern am liebsten an einer neuen Stelle im Headbereich.

Hintergrund ist, das ich die JS Dateien zusammen mixe und die dann im
<?= $this->head ?> Header ausgebe, allerdings setze ich in der fe_page
die Ausgabe ganz nach unten im DOM. Zweg's da Ladezeit und so!

Ich kann zwar in der /vendor/christianbarkowsky/rel-canonical/classes/ClassRelCanonical.php Zeile 93 die Stelle ändern, aber das wäre nicht updatesicher.

Kannst du dazu eine Option bereitstellen, das es wahlweise in einer anderen Stelle eingefügt werden kann.
Ich denke es macht Sinn im Theme unter Experten-Einstellungen da wo man das Seitentemplate auswählen kann entweder per Checkbox oder Select falls später Stellen/ Optionen dazu kommen.

Damit ist man flexibel genug und jeder kann entscheiden wo der TAG rein soll.

Viele Grüße

Markus

**Comment by baumannsven** [comment]
@codesache Du kannst dich nicht darauf verlassen das eine andere Erweiterung oder sogar Contao selbst sowas ähnliches macht. Daher solltest du im Prinzip prüfen ob dort noch was anderes drin ist im `$GLOBALS['TL_HEAD']`. Wenn du am Ende der Seite deine Scripte oder dergleichen ausgeben möchtest, wieso benutzt nicht den dafür vorgesehen Bereich `$GLOBALS['TL_BODY']`?

**Comment by christianbarkowsky** [comment]
Sehe ich auch so wie @baumannsven!
