### ISSUE TITLE
Drittanbieter Erweiterungen - canonical TAG

### ISSUE THREAD

**Issue by codesache** [christianbarkowsky/rel-canonical#16]
Hallo Christian,
kannst du für Drittanbieter Erweiterungen wie z.B den Custom Catalog
https://catalog-manager.org/ eine Anbindung bereitstellen. 

Aktuell ist das so nicht möglich auf den DetailsSeite das passende canonical auszugeben.
Beim Einsatz auf der Detailsseite kommt momentan <link rel="canonical" href="http://kunnde-xyz/details.html"> es müsste aber auf der Seite  http://kunde-xyz/details/max-mustermann.html <link rel="canonical" href="http://kunde-xyz/details/max-mustermann.html"> ausgegeben werden.

Viele Grüße

Markus

**Comment by christianbarkowsky** [comment]
Wie stellst du dir sowas genau vor @codesache

**Comment by codesache** [comment]
Hallo Christian,
ich habe es erst mal über die TPLs in dem Projekt gelöst.
Das habe ich oben eingefügt.

<?php
$canonical = "https://www.WEBSEITE-des-KUNDEN.de/details/$this->alias.html";
$alternate = "https://www.WEBSEITE-des-KUNDEN.de/details/$this->alias.html";
$GLOBALS['TL_HEAD'][] = '<link rel="canonical" href="'.$canonical.'">';
$GLOBALS['TL_HEAD'][] = '<link rel="alternate" hreflang="de" href="'.$alternate.'">';
?>

Der Alias steht ja zur Verfügung.


Viele Grüße
Markus

**Comment by christianbarkowsky** [comment]
Canonical URL are part of the Contao core since version 4.13
