### ISSUE TITLE
Attempted to load class "ModuleFaqReader/ModuleEventReader" from namespace "Contao"

### ISSUE THREAD

**Issue by netzarbeiter** [christianbarkowsky/rel-canonical#18]
Wenn das FAQ- und/oder Calendar-Bundle in Contao 4.4.* nicht installiert ist, erhalte ich beim Versuch das Produklist-Modul von Isotope zu bearbeiten einen Internal Server Error:
- Attempted to load class "ModuleFaqReader" from namespace "Contao". Did you forget a "use" statement for another namespace?
- Attempted to load class "ModuleEventReader" from namespace "Contao". Did you forget a "use" statement for another namespace?

In der Log-Datei steht folgendes:
- [2019-07-18` 09:34:22] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"ModuleFaqReader\" from namespace \"Contao\".\nDid you forget a \"use\" statement for another namespace? at …/vendor/christianbarkowsky/rel-canonical/modules/ModuleFaqReaderRelCannonical.php:24)"} []
- [2019-07-18 09:51:27] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"ModuleEventReader\" from namespace \"Contao\".\nDid you forget a \"use\" statement for another namespace? at …/vendor/christianbarkowsky/rel-canonical/modules/ModuleEventReaderRelCannonical.php:23)"} []

Es sollte im Bundle wohl geprüft werden, ob das FAQ- bzw. Calendar-Bundle überhaupt zur Verfügung steht.

Habe mir kurzerhand das FAQ- und Calendar-Bundle installiert um den Fehler zu umgehen.

**Comment by frontendschlampe** [comment]
selbiges Problem ...
