### ISSUE TITLE
Problem mit GET-Parametern bei News

### ISSUE THREAD

**Issue by bildschirmartist** [christianbarkowsky/rel-canonical#19]
Wenn man bei News-Items den Canonical auf "self" setzt, werden beim Aufruf des News-Beitrags mit zusätzlichen GET-Parametern (z.B. https://www.example.com/news/beispiel-eintrag?parameter=value&parameter2=wert) Diese Parameter mit im Canonical übernommen:

`<link rel="canonical" `href="https://www.example.com/news/beispiel-eintrag?parameter=value&parameter2=wert">`

Der Ergebnis-String von `Environment::get('request')` müsste an gegebener Stelle (`ModuleNewsReaderRelCannonical`) daher vor der Verwendung um eben diese Parameter bereinigt werden.

**Comment by codesache** [comment]
@christianbarkowsky Kannst du dir bitte die Anpassung ansehen. Vielen Dank Markus

**Comment by christianbarkowsky** [comment]
Fixed. Also fixed in the events and FAQ.

**Comment by codesache** [comment]
@christianbarkowsky Habe es eben lokal und auf meiner Seite getestet jetzt werden die Parameter bei der NewsDetails entnommen.

Vielen Dank
Markus
