### ISSUE TITLE
Unknown column 'newsInfiniteScroll_addCanonicalTag'

### ISSUE THREAD

**Issue by codedge** [christianbarkowsky/rel-canonical#21]
Hi,

wenn ich dein Module zusammen mit dem [Infinite Scroll Module](https://github.com/markocupic/contao-news-infinite-scroll-bundle) verwende und im Backend einen Artikel speichere erhalte ich folgende Fehlermeldung:

```
An exception occurred while executing 'UPDATE tl_module SET `newsInfiniteScroll_addCanonicalTag`='1' WHERE id='16'':

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'newsInfiniteScroll_addCanonicalTag' in 'field list'
```

<img width="1262" alt="grafik" src="https://user-images.githubusercontent.com/4409904/80311656-3c765200-87e1-11ea-81df-63d95cb29d85.png">

**Comment by christianbarkowsky** [comment]
HEy @codedge ... die Column gehört nicht zu meiner Erweiterung.

**Comment by codedge** [comment]
Hallo @christianbarkowsky,

das war wir fast klar. Ist es möglich deine Extension so generisch zu halten, dass sie auch mit anderen Extension zusammenarbeitet?

Ich kann mich jetzt quasi entscheiden, ob ich deine canonical tags oder den infinite scroll aus der anderen Extension haben will.

Es wäre schön, wenn beides zusammen funktionieren würde.

Hast du eine Idee?

**Comment by christianbarkowsky** [comment]
@codedge ... `Column not found: 1054 Unknown column 'newsInfiniteScroll_addCanonicalTag' in 'field list'` ... aktualisiere einfach eine Datenbank! Die Spalte newsInfiniteScroll_addCanonicalTag ist nicht vorhanden.
