### ISSUE TITLE
Fehler beim Composer Paket aktualisieren

### ISSUE THREAD

**Issue by akroii** [christianbarkowsky/rel-canonical#9]
Nachdem ich versucht habe die Erweiterung zu aktualisieren, kam im Composer diese Fehlermeldung: 
The "https://legacy-packages-via.contao-community-alliance.org/p/contao-legacy/dcawizard%2437ef95260a9637946b157489f02e5d2be0bfd5130948b96903675af5548cb7f0.json" file could not be downloaded (HTTP/1.1 404 Not Found)

**Comment by akroii** [comment]
Womöglich liegt der Fehler bei Contao Legacy
https://community.contao.org/de/showthread.php?63615-Fehler-Composer-Update-Suche

**Comment by christianbarkowsky** [comment]
Ich schließe die Issue - siehe Link!
